//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace X12ResourceTool.Spec {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("data_elements", Namespace="", IsNullable=false)]
    public partial class DataElementsType {
        
        private DataElementType[] data_eleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data_ele", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DataElementType[] data_ele {
            get {
                return this.data_eleField;
            }
            set {
                this.data_eleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DataElementType {
        
        private string ele_numField;
        
        private DataType data_typeField;
        
        private bool data_typeFieldSpecified;
        
        private string min_lenField;
        
        private string max_lenField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string ele_num {
            get {
                return this.ele_numField;
            }
            set {
                this.ele_numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DataType data_type {
            get {
                return this.data_typeField;
            }
            set {
                this.data_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_typeSpecified {
            get {
                return this.data_typeFieldSpecified;
            }
            set {
                this.data_typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string min_len {
            get {
                return this.min_lenField;
            }
            set {
                this.min_lenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string max_len {
            get {
                return this.max_lenField;
            }
            set {
                this.max_lenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    public enum DataType {
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        DT,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        R,
        
        /// <remarks/>
        TM,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        N0,
        
        /// <remarks/>
        N1,
        
        /// <remarks/>
        N2,
        
        /// <remarks/>
        N3,
        
        /// <remarks/>
        N4,
        
        /// <remarks/>
        N5,
        
        /// <remarks/>
        N6,
        
        /// <remarks/>
        N7,
        
        /// <remarks/>
        N8,
        
        /// <remarks/>
        N9,
    }
}
